<?php
/**
 * Created by PhpStorm.
 * User: damai
 * Date: 2019/3/26
 * Time: 16:10
 */
namespace backend\modules\form;

class Module extends \yii\base\Module
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

}